# Generated by Django 5.1.4 on 2025-01-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.RenameModel(
            old_name='Pet',
            new_name='Pets',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameModel(
            old_name='VaccinationRecord',
            new_name='VaccinationRecords',
        ),
    ]
