# Generated by Django 5.1.4 on 2025-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_appointment_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_type',
            field=models.CharField(choices=[('Walk-in', 'Walk-in'), ('Future Scheduled', 'Future Scheduled')], default='Future Scheduled', max_length=20),
        ),
    ]
