# Generated by Django 5.1.4 on 2025-03-12 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0003_appointments_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='appointment',
        ),
        migrations.AddField(
            model_name='billing',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='billing',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
