# Generated by Django 5.1.4 on 2025-03-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_billing_appointment_billing_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
