# Generated by Django 5.1.4 on 2025-03-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_billing_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='age',
        ),
        migrations.AddField(
            model_name='pets',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
